Repository hoyahozz/android-wanted-CustomKeyboardApp, pull requests merged in 2022-10, with the labels that each got.

#10 [ISSUE-005] 클립보드 기능 추가
  app/src/main/AndroidManifest.xml
  app/src/main/res/drawable/keyboard_item_frame.xml
  app/src/main/res/xml/xml.xml
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/preonboarding/customkeyboard/presentation/keyboard/KeyBoardService.kt
  presentation/src/main/java/com/preonboarding/customkeyboard/presentation/keyboard/KoreaLanguageMaker.kt
  presentation/src/main/java/com/preonboarding/customkeyboard/presentation/keyboard/QwertyKeyboard.kt
  presentation/src/main/res/layout/activity_main.xml
  presentation/src/main/res/layout/keyboard_item.xml
  presentation/src/main/res/layout/keyboard_view.xml
  presentation/src/main/res/layout/qwerty_keyboard.xml
  presentation/src/main/res/values/dimens.xml
  presentation/src/main/res/values/strings.xml
Labels: 🤗 FEATURE

#11 [ISSUE-008] Custom Keyboard 한글 입력 기능
  presentation/src/main/java/com/preonboarding/customkeyboard/presentation/keyboard/InputState.kt
  presentation/src/main/java/com/preonboarding/customkeyboard/presentation/keyboard/KoreaLanguageMaker.kt
  presentation/src/main/java/com/preonboarding/customkeyboard/presentation/keyboard/QwertyKeyboard.kt
  presentation/src/main/java/com/preonboarding/customkeyboard/presentation/keyboard/extension/DoubleEnableExtension.kt
Labels: 🤗 FEATURE

#15 docs - 김정호 README 작성
  README.md
Labels: ✍️ DOCS

#18 [ISUUE-009] 메인 페이지, 다이얼로그 UI 구현
  README.md
  domain/src/main/java/com/preonboarding/customkeyboard/domain/MyClass.kt
  presentation/src/main/java/com/preonboarding/customkeyboard/presentation/common/adapter/BindingAdapter.kt
  presentation/src/main/java/com/preonboarding/customkeyboard/presentation/model/Keyword.kt
  presentation/src/main/java/com/preonboarding/customkeyboard/presentation/model/Review.kt
  presentation/src/main/java/com/preonboarding/customkeyboard/presentation/ui/main/KeywordAdapter.kt
  presentation/src/main/java/com/preonboarding/customkeyboard/presentation/ui/main/MainActivity.kt
  presentation/src/main/java/com/preonboarding/customkeyboard/presentation/ui/main/ReviewAdapter.kt
  presentation/src/main/java/com/preonboarding/customkeyboard/presentation/ui/pay/PayDialog.kt
  presentation/src/main/res/drawable/bg_ad.png
  presentation/src/main/res/drawable/bg_gray_rounded_border.xml
  presentation/src/main/res/drawable/bg_keyboard_preview.png
  presentation/src/main/res/drawable/bg_main_rounded_border.xml
  presentation/src/main/res/drawable/bg_white_rounded_border.xml
  presentation/src/main/res/drawable/ic_arrow_down.xml
  presentation/src/main/res/drawable/ic_arrow_left_12dp.xml
  presentation/src/main/res/drawable/ic_arrow_left_18dp.xml
  presentation/src/main/res/drawable/ic_arrow_right.xml
  presentation/src/main/res/drawable/ic_character_expect.png
  presentation/src/main/res/drawable/ic_character_funny.png
  presentation/src/main/res/drawable/ic_character_funny_transparent.png
  presentation/src/main/res/drawable/ic_character_play.png
  presentation/src/main/res/drawable/ic_dummy.png
  presentation/src/main/res/drawable/ic_keyboard.xml
  presentation/src/main/res/drawable/ic_warning.xml
  presentation/src/main/res/drawable/ic_zem.xml
  presentation/src/main/res/layout/activity_main.xml
  presentation/src/main/res/layout/dialog_pay.xml
  presentation/src/main/res/layout/item_keyword.xml
  presentation/src/main/res/layout/item_review.xml
  presentation/src/main/res/values/colors.xml
  presentation/src/main/res/values/dimens.xml
  presentation/src/main/res/values/fonts.xml
Labels: 🎨 DESIGN, 🤗 FEATURE
